### ISSUE TITLE
Include .csproj to simplify build process

### ISSUE THREAD

**Issue by adamflaigg** [DeSinc/SallyBot#2]
It would make it a lot easier to build the project if the .csproj file was included as this uses a lot of nuget packages that aren't immediately clear what they are.

**Comment by DeSinc** [comment]
My bad, done now

**Comment by jvyden** [comment]
Generally you'll want to include the whole folder you have the project in - [GitHub Desktop](https://desktop.github.com/) is a good easy interface that talks to GitHub directly (instead of uploading files to GitHub on the website)


You'll probably want a gitignore file to exclude built files, models, etc.
A good template for Visual Studio can be found here, just name it `.gitignore` at the root of the folder your project is in: https://github.com/github/gitignore/blob/main/VisualStudio.gitignore

**Comment by adamflaigg** [comment]
> Generally you'll want to include the whole folder you have the project in - [GitHub Desktop](https://desktop.github.com/) is a good easy interface that talks to GitHub directly (instead of uploading files to GitHub on the website)
> 
> You'll probably want a gitignore file to exclude built files, models, etc. It prevents files from being uploaded to GitHub. A good template for Visual Studio can be found here, just name it `.gitignore` at the root of the folder your project is in: https://github.com/github/gitignore/blob/main/VisualStudio.gitignore

yeah I've been going through I realized that there is still a lot missing that this project interfaces with (specifically the language model I've been having issues with trying to figure out how/what to import and use the interface with it). Probably would be best to upload the whole project folder and remove anything like tokens/keys and stuff.

**Comment by DeSinc** [comment]
> 

I just added all of the discord code and the includes etc. to program.cs and also the MainGlobal.cs file that holds definitions for Server and Client vars that get used a few times.

**Comment by Tangerine-C** [comment]
I've been having context errors (CS0103), even with the new MainGlobal.cs file. vars "Client", "Commands", "Socket", "typing", "typingticks", "thinking" are all included. I gave Client & Server the prefix RoboSinc.MainGlobal(.Client/.Server) and it seem to fix the context error but with special cases like "Client_MessageRecieved" and many similar one following it, the prefix RoboSinc.MainGlobal did not work. This may just be something that Visual Studio C# has issues with, though the changes made to the code since the previous version did fix a lot of the problems. I'm not completely used to C# so the problems I'm dealing with maybe easy to fix.

**Comment by DeSinc** [comment]
I just added the last pieces now to the code. Now it all builds and runs first try, give it a go. Program.cs has been totally rewritten and reorganised etc.
