### ISSUE TITLE
The Ai website generate a good one and the discord bot not

### ISSUE THREAD

**Issue by ZEAROo** [DeSinc/SallyBot#35]
so when stable-diffusion-webui, the website does it correct (the localhost)  but when use the bot on discord it only seems like it picks the model but does not generate anything with it. its hard to explain so see the pictures

i said this to the bot of what to generate

the one on the localhost link
![Screenshot_2](https://github.com/DeSinc/SallyBot/assets/140189621/c53efbe2-c31a-4803-99f0-353e730d2eb8)

and this one in discord
![image](https://github.com/DeSinc/SallyBot/assets/140189621/34233677-9f40-4bad-b90a-e146a7f660fc)

I dont know what is wrong, the only thing i can think off is that the bot doesn't copy the image generated from the website 

(i got another problem too but i want to fix this first)
can anyone help me with this please ?

(sorry for my grammar too)

**Comment by DeSinc** [comment]
In SallyBot code, in the Functions.cs file, there is a prompt that guides how Sally should look. You can find it by searching that file for "blonde" and it will come up.

![image](https://github.com/DeSinc/SallyBot/assets/12345584/6a4ef0c5-7003-48bf-8c94-e8d1cca18a9c)

I made it blonde for the public bot but you can replace with Brown hair instead of Blonde hair. With the image generator you generally have to specify this so that it doesn't give you something random, although brown hair seems to be the most common generation with most of these models anyway - but it will give you a surprise hair colour from time to time anyway so it's good to specify it upfront which is what that space in the picture is for
