### ISSUE TITLE
"Missing required gateway intent" When it's enabled

### ISSUE THREAD

**Issue by FusionBrah** [DeSinc/SallyBot#42]
G'day,
When I am running the bot I am getting the following output in the console:
```
|12/06/2024 1:16:19 PM - Gateway| System.InvalidOperationException: Missing required gateway intent GuildMembers in order to execute this operation.
   at Discord.WebSocket.DiscordSocketClient.EnsureGatewayIntent(GatewayIntents intents)
   at Discord.WebSocket.DiscordSocketClient.DownloadUsersAsync(IEnumerable`1 guilds)
   at Discord.WebSocket.DiscordSocketClient.<ProcessMessageAsync>b__158_0(Task x)
 ```
 I have confirmed that the correct intent's are enabled on the application on the Discord Dev portal.
 
![Screenshot 2024-06-12 at 1 35 52 PM](https://github.com/DeSinc/SallyBot/assets/49272518/da4d6364-58ee-4821-a0bb-e0223ed004f1)

Cheers mate.

**Comment by DeSinc** [comment]
This error can for the moment be safely ignored and doesn't break or affect anything in the bot, however I will take a look at correcting this as it is probably just a quick thing to add to my code. I'll check it out

**Comment by FusionBrah** [comment]
Will this affect if the bot can @ reply to someones message?

**Comment by DeSinc** [comment]
> Will this affect if the bot can @ reply to someones message?

No all of that has been working fine. (Edit: I deliberately set the bot to either not ping for replies or to just not reply at all because it got confused with it in the past, replying to someone 2 messages ago but hitting reply on the last person to type)

I've just put in a line that fixes this by adding the GuildMembers intent at initialisation. I'm not sure if anything actually uses it, but it might. I had a think about it and it might have affected its ability to see name changes like if you change the bot's name on discord for example it may not update in the program, but I'm not sure as I haven't tested it.

In either case it will all be fixed now, but nothing really should have changed for the most part.
