### ISSUE TITLE
Changes made to the lLLM?  Also schizophrenic sally?

### ISSUE THREAD

**Issue by soarn** [DeSinc/SallyBot#5]
Hi Mr.Sinc, what changes did you make to the LLM that made it stop?  I assume this is why Sally is schizophrenic and talks to herself?

As far as I can tell I have everything working correctly, except for stable diffusion, I haven't installed that yet.

Thank you for giving Sally life.

![image](https://user-images.githubusercontent.com/11000195/229648572-35f83cee-c245-4c10-9cff-f593b46d0935.png)
---

![image](https://user-images.githubusercontent.com/11000195/229648649-9868c8c3-23e3-4b60-ad0d-e46c9360cdfc.png)
![image](https://user-images.githubusercontent.com/11000195/229648670-60a629b4-4feb-4e41-a212-5efd63b6bb0c.png)

**Comment by DeSinc** [comment]
Here you go, uploaded the index.js file here: https://cdn.discordapp.com/attachments/439422392201248779/1092653447490306098/index.js

Alternatively you can access the Dalai discord and see this message where I sent it there too: https://discord.com/channels/1052861702561075230/1085649349586985010/1090498330800443414

So basically I downloaded the dalai source from the dalai github and modified it directly, built it, then ran the npx dalai serve command FROM the custom source code folder I made. so for example in command prompt, after dling the source and swapping out the index.js and building with visual studio code:

cd dalaiCustomSourceFoldernameHere
npx dalai serve

^ that then builds the project into the default folder C:\users\name\dalai\ but using your swapped source code. it has to do this "indextree" thing or whatever for like 20 seconds every time you run the custom code because I don't know how to make that go away.

And then that's it, once it's running it now accepts stop emits from socketio.
