### ISSUE TITLE
Missing .editorconfig

### ISSUE THREAD

**Issue by nmbro** [DeSinc/SallyBot#7]
While not causing any issues, it looks like you could have included a .editorconfig with your repository.

Usually helps if people contribute to your code.

https://github.com/DeSinc/SallyBot/blob/c87b5b529268293152269e9ca1057248bd0ff8b5/sallybot.csproj#L12

**Comment by DeSinc** [comment]
not sure where this file is, I have one that's in my build in the debug folder but don't think it's the one you need

**Comment by nmbro** [comment]
@DeSinc so `..\.editorconfig` would mean that it's in the folder above your SallyBot directory - could you check there?

**Comment by DeSinc** [comment]
Ah here it is


[*.cs]

# CS4014: Because this call is not awaited, execution of the current method continues before the call is completed
dotnet_diagnostic.CS4014.severity = silent

# IDE0028: Simplify collection initialization
dotnet_style_collection_initializer = true


Where would I upload it in the github since it's meant to be in the folder above?
